### ISSUE TITLE
[Bug] Crash on startup with AiMesh mixed models (XT8 + RT-AX56/58) using HTTPS – AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by johhiq** [Vaskivskyi/asusrouter#737]
### The problem

After upgrading Home Assistant (Docker) to 2025.12.x, the asusrouter integration fails to set up when using HTTPS (SSL) in a mixed AiMesh environment.

The integration crashes during the onboarding/AiMesh phase with:
`AttributeError: 'str' object has no attribute 'get'`

Disabling SSL (forcing HTTP) works as a workaround.

This appears to be related to how onboarding/AiMesh data is parsed when different router models and backhaul types are present.

Looks related to the HA Core 2025.12.2 ASUSWRT setup regressions reported in HA core issues (e.g. #158288 / #158291) and community thread ‘Asuswrt broke with 2025.12.2’

Environment
	•	Home Assistant: 2025.12.x (Docker)
	•	Integration: ha-asusrouter (latest from HACS)
	•	Connection method: HTTPS / SSL enabled
	•	Port: 0 (auto-select)

Router / Mesh setup
	•	AiMesh enabled
	•	Routers:
	•	2 × XT8
	•	1 × RT-AX56
	•	1 × RT-AX58
	•	Backhaul:
	•	Some nodes via Ethernet
	•	Some nodes via Wi-Fi
	•	Firmware: Stock Asus firmware (no Merlin)

⸻

Steps to reproduce
	1.	Set up asusrouter integration with:
	•	SSL connection = true
	•	Port = 0 (auto)
	2.	Restart Home Assistant
	3.	Integration fails during setup

⸻

Expected behavior

The integration should successfully initialize and parse AiMesh onboarding data for all nodes, regardless of router model or backhaul type.

⸻

Actual behavior

Integration crashes during setup with:
`File ".../asusrouter/modules/endpoint/onboarding.py", line 98, in process_aimesh_node
level = safe_int(data.get("level", "0"))
AttributeError: 'str' object has no attribute 'get'`

Workaround
	•	Disable SSL (HTTPS) and run the integration over HTTP
→ Integration then starts successfully.

### Python version

3.13.9

### Your device model

AX XT8

### Firmware type

Stock

### Firmware version

3.0.0.4.388_24768

**Comment by Vaskivskyi** [comment]
Hello, thanks for your report! The issue is indeed related to the HA version 2025.12.2 and AsusRouter version `1.21.1`

The issue is already fixed in AsusRouter `1.21.3` and HA version 2025.12.3

Due to now both the in-built AsusWRT and custom AsusRouter integrations having the same backend dependency, unfortunately, this issue propagated to both integrations. I am sorry for this.

Please, check the behaviour with HA 2025.12.3+ and reopen the issue if you still experiencing this one.
